export const localStorage = [
  {
    date: "2023-05-13",
    monthYear: "Mar 2023",
    transactionType: "Personal Leaving",
    fromAccount: "Personal Account",
    toAccount: "Real Living",
    amount: 1399,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "jay",
  },
  {
    date: "2022-04-03",
    monthYear: "Apr 2023",
    transactionType: "Home Expense",
    fromAccount: "Core Realtors",
    toAccount: "Big Block",
    amount: 140,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "vishwa",
  },
  {
    date: "2021-06-23",
    monthYear: "Dec 2023",
    transactionType: "Personal Leaving",
    fromAccount: "My Dream Home",
    toAccount: "Big Block",
    amount: 10,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "arpish",
  },
  {
    date: "2022-08-19",
    monthYear: "Oct 2023",
    transactionType: "Home Expense",
    fromAccount: "Real Living",
    toAccount: "Core Realtors",
    amount: 20000,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "chaitali",
  },
  {
    date: "2023-11-13",
    monthYear: "Feb 2023",
    transactionType: "Income",
    fromAccount: "Full Circle",
    toAccount: "Real Living",
    amount: 10058,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "parth",
  },
  {
    date: "2022-02-11",
    monthYear: "Nov 2023",
    transactionType: "Personal Leaving",
    fromAccount: "Big Block",
    toAccount: "Personal Account",
    amount: 835,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "tushar",
  },
  {
    date: "2018-04-10",
    monthYear: "Aug 2023",
    transactionType: "Home Expense",
    fromAccount: "Real Living",
    toAccount: "My Dream Home",
    amount: 1400,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "nisarg",
  },
  {
    date: "2017-01-01",
    monthYear: "June 2023",
    transactionType: "Income",
    fromAccount: "Personal Account",
    toAccount: "Full Circle",
    amount: 1800,
    recepit: "https://picsum.photos/id/237/200/300",
    notes: "dev",
  },
];
